### ISSUE TITLE
[Feature Request]:  API Convert Markdown to PDF

### ISSUE THREAD

**Issue by clabnet** [Stirling-Tools/Stirling-PDF#1931]
### Feature Description

It should be useful an API to create a pdf from a markdown file. 
see also #1568

### Why is this feature valuable?

It seems missing from http://localhost:8080/swagger-ui/index.html

### No Duplicate of the Feature

- [X] I have verified that there are no existing features requests similar to my request.

**Comment by akashsin63** [comment]
Hello @clabnet ,
I'd like to take on the "API Convert Markdown to PDF" feature request. I believe I can implement it efficiently and would love the opportunity to contribute. Could you please assign this issue to me?

**Comment by Frooodle** [comment]
Sounds good!

**Comment by Frooodle** [comment]
Just to add to this, we actually did support markdown to pdf till a few weeks ago...
we did markdown to HTML
and then HTML to PDF

HTML to pdf was disabled due to some security issues at the time you can find code here
https://github.com/Stirling-Tools/Stirling-PDF/blob/main/src/main/java/stirling/software/SPDF/controller/api/converters/ConvertMarkdownToPdf.java

**Comment by akashsin63** [comment]
Thank you for the heads up , Saw that new code for markdown to pdf  as I pulled the new changes I m working on the feature taking reference will be raising PR in some hours Thanks. :)

**Comment by clabnet** [comment]
Thank you all!
