### ISSUE TITLE
[Bug]: Rotate is not persisted for sign action

### ISSUE THREAD

**Issue by thecoffeebin** [Stirling-Tools/Stirling-PDF#2074]
### Installation Method

Docker

### The Problem

Hi,
I've updated to the latest App Version: 0.30.1
I've rotated a PDF using the Rotate feature and then saved it to a file on my laptop
then I go to Sign and loaded the PDF which was rotated earlier and it's displayed correcly on my screen (portrait)
Once I added my signature and saved the file to my laptop, the signature is appear horizontal and not according to the orientation of the PDF.
I suspect it got the original orientation (Horizontal) of the PDF during the Sign action.

Please can you look into this and fix it.

### Version of Stirling-PDF

0.30.1

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by jgdub** [comment]
Can confirm the same here.

1 - Rotate,
2 - Sign,

The result signatures out of position and are rotated 90 degrees.

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by ENTXawp** [comment]
Hi, 

Unfortunatly this issue still presists on both of my stirling-pdf containers. 
Running frooodle/s-pdf:latest (App Version: 0.33.1)

when using a pdf in portrait it works fine.
[sample.pdf](https://github.com/user-attachments/files/17828914/sample.pdf)
![image](https://github.com/user-attachments/assets/d7c14cbd-b79f-48bf-890a-27a4400673eb)
![image](https://github.com/user-attachments/assets/6bde56bd-20c5-433d-9325-05383407447a)
[sample_signed.pdf](https://github.com/user-attachments/files/17828915/sample_signed.pdf)

But when the orientation is landscape the issue is still there.
[sample_rotated.pdf](https://github.com/user-attachments/files/17828927/sample_rotated.pdf)
![image](https://github.com/user-attachments/assets/f1c9333c-e056-4c2a-9c32-04c0e89102c2)
![image](https://github.com/user-attachments/assets/a901cb3c-8a2a-400b-b66a-4a70667c691d)
[sample_rotated_signed.pdf](https://github.com/user-attachments/files/17828939/sample_rotated_signed.pdf)

Ive attached the files.
