### ISSUE TITLE
[Bug]: Search bar on homepage doesn't work with collapsible menus 

### ISSUE THREAD

**Issue by Frooodle** [Stirling-Tools/Stirling-PDF#2264]
### Feature Description

Search bar on homepage doesn't work with collapsible menus
If the menu is collapsed and you do a search it doesn't detect the elements since they are removed from UI

Additionally when searching
![image](https://github.com/user-attachments/assets/c4c6946b-b4e0-4ea2-aeb4-ce77dd30f48e)
 it shows all the other menus but empty which adds nothing to the UI and only clutter
 Suggestion is to remove all empty fields when this happens

### Why is this feature valuable?

Clean and understandable UI

### No Duplicate of the Feature

- [X] I have verified that there are no existing features requests similar to my request.

**Comment by omar-ahmed42** [comment]
Can I contribute in solving this bug?

Also, can you clarify `"If the menu is collapsed and you do a search it doesn't detect the elements since they are removed from UI"`? As I tried searching with collapsed menus and it correctly displayed the feature groups that has the cards matching the search criteria and when expanded it actually displayed the cards matching the criteria (as demonstrated in the attached GIF).

![cluttered-search-ui](https://github.com/user-attachments/assets/94485889-21b8-4b70-a7ac-ece06572c8b2)


As for hiding/removing empty menus (accordions/feature-groups) to clean the UI from clutter (as mentioned in the second part of the issue), I have an idea of what's causing the issue and might start upon having the issue assigned to me.

**Comment by Frooodle** [comment]
A user performing a search shouldn't need to manually expand each element to check if their searches entry is inside it 
The search should auto expand them

**Comment by omar-ahmed42** [comment]
Thank you for the clarification
