### ISSUE TITLE
Image to PDF has a very low file size limit

### ISSUE THREAD

**Issue by Kevin-Aaaquil** [Stirling-Tools/Stirling-PDF#370]
The conversion of images to pdf fails if the collective size of uploads is greater than 2MB

**Comment by Frooodle** [comment]
How does this 'fail' for you?

**Comment by Kevin-Aaaquil** [comment]
> How does this 'fail' for you?

It returns a 413 code everytime the collective size is greater that 2MB

**Comment by Frooodle** [comment]
This shouldn't be unique to any operation.
Are you running it behind nginx or anything?

**Comment by daemon-byte** [comment]
If you are using nginx as a reverse proxy then add these options to your config. Then tweak to your needs

`
proxy_buffering      off;
client_max_body_size 0;
proxy_request_buffering off;
`

**Comment by anish42** [comment]
Hello, I am getting the same issue, any images above 2mb and the 'Image to PDF' fails.

Error : Internal Server Error:Cannot invoke "java.awt.image.BufferedImage.getColorModel()" because "image" is null

I am running this currently in Docker, accessing it directly.

Is there something that I need to put in the docker compose config maybe? to increase this limit

**Comment by lenybernard** [comment]
Indeed, same for me, docker 

![image](https://github.com/Frooodle/Stirling-PDF/assets/618536/1ea2f9ea-9fea-49ee-9b38-57479bbc3194)
![image](https://github.com/Frooodle/Stirling-PDF/assets/618536/90369041-afe0-4610-bac0-83c240f06911)


There is nothing in docker compose logs.

**Comment by Frooodle** [comment]
can you post your full log?

**Comment by Frooodle** [comment]
Closing due to no comments and can not repeat
