### ISSUE TITLE
Contribution offer: Multi-Tool UX/UI remake

### ISSUE THREAD

**Issue by berserkwarwolf** [Stirling-Tools/Stirling-PDF#478]
Hi, I just installed Stirling-PDF and was blown away by it's features. Congrats on that!

I was wondering if you were open to accept a UX/UI redesign proposal.

I would be willing to offer my spare time to design an interface to enable the user to execute all operations already implemented, in one intuitive single page. Similar in concept to Adobe's Acrobat Pro CC web app.

I would be using exclusively FOSS tools like Inkscape for drafts and [Penpot](https://penpot.app/) for the final deliverables.

However, I understand that this would mean a lot of programming on your part, so that's why I'm asking if you would be up for the task, as I am not a programmer.

**Comment by Frooodle** [comment]
Hey sorry for not replying to this.
sadly it is as you saw, we were not willing to do any UI redesigns due to the work load
We are however currently developing a V2 of Stirling PDF feel free to drop a chat in the devs channel on discord and we can discuss how it looks and what you and others think, Could be useful in future!
