### ISSUE TITLE
Add pkcs7 format for a digital signature.

### ISSUE THREAD

**Issue by albanobattistella** [Stirling-Tools/Stirling-PDF#630]
Hi,
thanks for your great work!
Could you add pkcs7 format, the one used for signing via smart cards, and therefore the digital signature?
If you interface with the browser certificate manager to obtain it, and make the software create at least a basic signature, CADES Baseline, then it can be compliant for the current qualified electronic signature exemple:
https://sourceforge.net/projects/j4sign/files/freesigner/
Thanks again for your beautiful work! 
Happy new Year!
Regards,
A.

**Comment by Frooodle** [comment]
Currently cert signing has some issues so we wont be adding anything to it until that issue is resolved.
We are looking into this tho, once issue is resolved we may be able to add other formats

https://github.com/Stirling-Tools/Stirling-PDF/issues/364

**Comment by sbplat** [comment]
#650 fixes the PDF signing issue and introduces support for a new format: Java Keystore. Since PKCS7, as well as other formats can be converted into JKS using the `keytool` CLI program, there are no plans to implement dedicated support for each specific format.

The `keytool` program is included with any standard JDK/JRE distribution. You can find it under `%JAVA_HOME%/bin` on Windows.
