### ISSUE TITLE
[Bug] App version shows as 0.0.0

### ISSUE THREAD

**Issue by supaflyster** [Stirling-Tools/Stirling-PDF#668]
Hi! Minor thing, but looks like after upgrade to 0.19.0 app version in Settings window shows as 0.0.0 and offers to upgrade to 0.19.0.

<img width="502" alt="Screenshot 2024-01-07 at 10 45 18" src="https://github.com/Stirling-Tools/Stirling-PDF/assets/6348312/ff29ec2c-6b59-4a50-bd15-c8bb96b2f647">

**Comment by JigSawFr** [comment]
Same issue, docker package 19.0.

**Comment by Frooodle** [comment]
Can confirm the same my side, will investigate

**Comment by supaflyster** [comment]
did quick check, and noticed that api returns null for version. Also found this idea - https://stackoverflow.com/a/38204640 

`Please make sure you have a newline at the end of the manifest. If there is no newline character at the end, 
getImplementationVersion() will return null.`

Might be related to the removing of  eol commit - https://github.com/Stirling-Tools/Stirling-PDF/commit/6fe268adcb6fc6db1916dab2b183a622a8c5bcc1

**Comment by Node815** [comment]
I am having the same issue - I am using docker, removed the data files where the config was stored, ran docker system prune -a to remove it fully.  Then ran the compose up again. 

My Compose:

```version: '3.3'
services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    ports:
      - '8082:8080'
    volumes:
#      - /location/of/trainingData:/usr/share/tesseract-ocr/4.00/tessdata #Required for extra OCR languages
      - /mnt/storage/docker/appdata/stirlingpdf:/configs
#      - /location/of/customFiles:/customFiles/
    environment:
      - DOCKER_ENABLE_SECURITY=false
```

What I see:
![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/20736534/e61e622a-6d3f-4b6d-bd1f-e10a5acc018e)

This seems to make it think there's an update available as well?  If so, I'm guessing it is because version is 0.0.0

**Comment by sbplat** [comment]
The fix has been pushed to the main branch but hasn't been released yet. If this is really urgent, you could build it from source.
