### ISSUE TITLE
[Feature request] Translate a pdf from one language to another and return the already translated pdf

### ISSUE THREAD

**Issue by NexusEFR** [Stirling-Tools/Stirling-PDF#673]
The truth is that there are fewer and fewer things left to improve in your project! It's amazing and very good!. So maybe you're suggesting this improvement and you already have it planned or it's been requested. 

Or maybe it's something too complex, but I think it would be an incredible tool, to be able to upload a pdf in one language and have your platform return it in another language with the same structure as the pdf, or maybe in a docx it could also be valid if it's easier to develop. 

I edit, I forgot another topic: I don't know if a platform like the one you have developed could do something that I have been looking for a long time in docker or selfhosted, it would be to monitor a folder and be able to print on the default printer that is configured, so that all the PDFs that arrive in that folder are printed instantly. There are really tedious workloads when receiving hundreds of PDFs in multiple emails.

In any case, I appreciate the assessment of this improvement. Best regards.

**Comment by Frooodle** [comment]
Hey good to see you, I know you been here since Stirling-PDF first started!

As it is sadly translations are not yet possible.
Once we find a good way to provide realtime text editting within the PDF we can approach this but since we are not currently able to edit the text we can no provide translations etc. 
One of the main reasons is the "maintain formatting" part
a 4 letter word could be replaced with a 10 letter translation, with formatting in mind thats a huge mess for PDFs

So no plans to support currently sorry

**Comment by sbplat** [comment]
@NexusEFR could you create a new issue for the second feature request? Thanks!
