### ISSUE TITLE
Documentation related to Supported Languages

### ISSUE THREAD

**Issue by cloud-erik** [Stirling-Tools/Stirling-PDF#702]
It looks like the documentation and examples related to the supported languages are outdated.
just tested and found e.g. 
`SYSTEM_DEFAULTLOCALE: de_DE`
as shown in the documentation does not work, but
`SYSTEM_DEFAULTLOCALE: de-DE` (with "-" instead of "_" works fine.

**Comment by hurriedlu** [comment]
Thank you, after tuning for a long time I realized it was still the default language, and I didn't find the error message, I thought I had to download the language pack separately. After reading this issus I realized I should use '-' instead of '_'.This reply was translated into English via Deepl, there may be inaccuracies in it, please understand.

**Comment by cloud-erik** [comment]
Thanks for confirmation. I already created a pull request for changing the compose examples. Not sure about the general documentation.

**Comment by JFPCreations** [comment]
To add to this thread :
This worked       
- SYSTEM_DEFAULTLOCALE=fr-FR
but not       
- SYSTEM_DEFAULTLOCALE: fr-FR
Error: failed to deploy a stack: validating /data/compose/243/v4/docker-compose.yml: services.stirling-pdf.environment.0 must be a string
